export const GET_ALL_CAPTAINS_SUCCESS = "GET_ALL_CAPTAINS_SUCCESS";
export const GET_ALL_CAPTAINS_ERROR = "GET_ALL_CAPTAINS_ERROR";
export const GET_ALL_TEAMS_SUCCESS = "GET_ALL_TEAMS_SUCCESS";
export const GET_ALL_TEAMS_ERROR = "GET_ALL_TEAMS_ERROR";


export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GET_ERRORS = "GET_ERRORS";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POSTS_ERROR";
export const LOGUT_SUCCESS = "LOGUT_SUCCESS";
export const GET_MY_POSTS = "GET_MY_POSTS";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_UNLIKE_SUCCESS = "POST_UNLIKE_SUCCESS";
